// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.0
// source: dns_query_service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// DNSQueryServiceClient is the client API for DNSQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DNSQueryServiceClient interface {
	// Single DNS query
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Batch DNS queries (efficient for multiple lookups)
	BatchQuery(ctx context.Context, in *BatchQueryRequest, opts ...grpc.CallOption) (*BatchQueryResponse, error)
	// Streaming queries (persistent connection for multiple queries)
	StreamQuery(ctx context.Context, opts ...grpc.CallOption) (DNSQueryService_StreamQueryClient, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dnsQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSQueryServiceClient(cc grpc.ClientConnInterface) DNSQueryServiceClient {
	return &dnsQueryServiceClient{cc}
}

func (c *dnsQueryServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/squawkdns.query.DNSQueryService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dnsQueryServiceClient) BatchQuery(ctx context.Context, in *BatchQueryRequest, opts ...grpc.CallOption) (*BatchQueryResponse, error) {
	out := new(BatchQueryResponse)
	err := c.cc.Invoke(ctx, "/squawkdns.query.DNSQueryService/BatchQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dnsQueryServiceClient) StreamQuery(ctx context.Context, opts ...grpc.CallOption) (DNSQueryService_StreamQueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &DNSQueryService_ServiceDesc.Streams[0], "/squawkdns.query.DNSQueryService/StreamQuery", opts...)
	if err != nil {
		return nil, err
	}
	x := &dnsQueryServiceStreamQueryClient{stream}
	return x, nil
}

func (c *dnsQueryServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/squawkdns.query.DNSQueryService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSQueryService_StreamQueryClient is the client API for DNSQueryService_StreamQuery streaming RPC method.
type DNSQueryService_StreamQueryClient interface {
	Send(*QueryRequest) error
	Recv() (*QueryResponse, error)
	grpc.ClientStream
}

type dnsQueryServiceStreamQueryClient struct {
	grpc.ClientStream
}

func (x *dnsQueryServiceStreamQueryClient) Send(m *QueryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dnsQueryServiceStreamQueryClient) Recv() (*QueryResponse, error) {
	m := new(QueryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DNSQueryServiceServer is the server API for DNSQueryService service.
// All implementations must embed UnimplementedDNSQueryServiceServer
// for forward compatibility
type DNSQueryServiceServer interface {
	// Single DNS query
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Batch DNS queries (efficient for multiple lookups)
	BatchQuery(context.Context, *BatchQueryRequest) (*BatchQueryResponse, error)
	// Streaming queries (persistent connection for multiple queries)
	StreamQuery(DNSQueryService_StreamQueryServer) error
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDNSQueryServiceServer()
}

// UnimplementedDNSQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDNSQueryServiceServer struct {
}

func (UnimplementedDNSQueryServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDNSQueryServiceServer) BatchQuery(context.Context, *BatchQueryRequest) (*BatchQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchQuery not implemented")
}
func (UnimplementedDNSQueryServiceServer) StreamQuery(DNSQueryService_StreamQueryServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamQuery not implemented")
}
func (UnimplementedDNSQueryServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDNSQueryServiceServer) mustEmbedUnimplementedDNSQueryServiceServer() {}

// UnsafeDNSQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as adding methods to DNSQueryServiceServer will
// result in compilation errors.
type UnsafeDNSQueryServiceServer interface {
	mustEmbedUnimplementedDNSQueryServiceServer()
}

func RegisterDNSQueryServiceServer(s grpc.ServiceRegistrar, srv DNSQueryServiceServer) {
	s.RegisterService(&DNSQueryService_ServiceDesc, srv)
}

func _DNSQueryService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSQueryServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squawkdns.query.DNSQueryService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSQueryServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSQueryService_BatchQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSQueryServiceServer).BatchQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squawkdns.query.DNSQueryService/BatchQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSQueryServiceServer).BatchQuery(ctx, req.(*BatchQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSQueryService_StreamQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DNSQueryServiceServer).StreamQuery(&dnsQueryServiceStreamQueryServer{stream})
}

type DNSQueryService_StreamQueryServer interface {
	Send(*QueryResponse) error
	Recv() (*QueryRequest, error)
	grpc.ServerStream
}

type dnsQueryServiceStreamQueryServer struct {
	grpc.ServerStream
}

func (x *dnsQueryServiceStreamQueryServer) Send(m *QueryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dnsQueryServiceStreamQueryServer) Recv() (*QueryRequest, error) {
	m := new(QueryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DNSQueryService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSQueryServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squawkdns.query.DNSQueryService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSQueryServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSQueryService_ServiceDesc is the gRPC service descriptor for DNSQueryService service.
// It should be used only by the generated gRPC code.
var DNSQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "squawkdns.query.DNSQueryService",
	HandlerType: (*DNSQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _DNSQueryService_Query_Handler,
		},
		{
			MethodName: "BatchQuery",
			Handler:    _DNSQueryService_BatchQuery_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DNSQueryService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamQuery",
			Handler:       _DNSQueryService_StreamQuery_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dns_query_service.proto",
}
