apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - valkey-deployment.yml
  - valkey-service.yml
  - dns-server-deployment.yml
  - dns-server-service.yml
  - dns-client-deployment.yml
  - dns-client-service.yml
  - manager-deployment.yml
  - manager-scheduler-deployment.yml
  - networkpolicy-default-deny.yml
  - networkpolicy-dns.yml
  - networkpolicy-manager.yml
  - networkpolicy-data.yml
