apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - valkey-deployment.yaml
  - valkey-service.yaml
  - dns-server-deployment.yaml
  - dns-server-service.yaml
  - dns-client-deployment.yaml
  - dns-client-service.yaml
