apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: squawk
  labels:
    app.kubernetes.io/name: squawk
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: valkey
spec:
  type: ClusterIP
  ports:
  - name: valkey
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: squawk
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: valkey
