{{- if .Values.dhcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dhcp-server
  namespace: {{ include "squawk.namespace" . }}
  labels:
    {{- include "squawk.dhcpServer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: dhcp-http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    {{- include "squawk.dhcpServer.selectorLabels" . | nindent 4 }}
{{- end }}
