apiVersion: v1
kind: Service
metadata:
  name: dns-client
  namespace: {{ include "squawk.namespace" . }}
  labels:
    {{- include "squawk.dnsClient.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: dns-udp
    port: 53
    targetPort: {{ .Values.dnsClient.listenPort }}
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: {{ .Values.dnsClient.listenPort }}
    protocol: TCP
  selector:
    {{- include "squawk.dnsClient.selectorLabels" . | nindent 4 }}
