apiVersion: v1
kind: Service
metadata:
  name: k8s-dns
  namespace: {{ include "squawk.namespace" . }}
  labels:
    {{- include "squawk.labels" . | nindent 4 }}
    app.kubernetes.io/component: k8s-dns
spec:
  type: ClusterIP
  ports:
  - name: dns-udp
    port: 53
    targetPort: {{ .Values.k8sDns.listenPort }}
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: {{ .Values.k8sDns.listenPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "squawk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: k8s-dns
