apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: {{ include "squawk.namespace" . }}
  labels:
    {{- include "squawk.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
  - name: valkey
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: squawk
    app.kubernetes.io/component: cache
