apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-server
  namespace: squawk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dns-server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-client
  namespace: squawk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dns-client
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: squawk
spec:
  replicas: 1
