apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-client
  namespace: squawk
spec:
  template:
    spec:
      containers:
      - name: dns-client
        image: ghcr.io/penguintechinc/squawk-dns-client:latest
        imagePullPolicy: Always
