apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-server
  namespace: squawk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dns-server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squawk-client
  namespace: squawk
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-server
  namespace: squawk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dhcp-server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntp-server
  namespace: squawk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ntp-server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
